#!/bin/bash
echo "🔍 检查服务状态..."
echo ""
echo "📊 后端服务器 (端口 3001):"
curl -s http://localhost:3001/api/health && echo "✅ 后端运行正常" || echo "❌ 后端无法访问"
echo ""
echo "📊 前端服务器 (端口 3000):"
lsof -i :3000 | grep LISTEN && echo "✅ 端口 3000 正在监听" || echo "⚠️ 端口 3000 未监听"
echo ""
echo "🔄 React 进程:"
ps aux | grep react-scripts | grep -v grep || echo "❌ 未找到 React 进程"
echo ""
echo "📝 建议:"
echo "1. 在浏览器中打开: http://localhost:3000"
echo "2. 如果浏览器无法访问,检查浏览器控制台错误"
echo "3. 后端 API 文档: http://localhost:3001/api/health"
